# Generated by Django 5.0.2 on 2024-03-16 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_utilisateur_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='description',
            new_name='BIO',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='cv',
            new_name='CV',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='personal_email',
            new_name='public_email',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='in_profile_phone_number',
            new_name='public_phone_number',
        ),
    ]
