# Generated by Django 5.0.2 on 2024-03-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_description_utilisateur_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
