# Generated by Django 5.0.2 on 2024-03-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_utilisateur_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='staticfiles/Assets/profile_pictures/'),
        ),
    ]
