# Generated by Django 5.0.2 on 2024-03-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_research_recherche_document_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='fax',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='localisation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='date_inscription',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='date_integration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='poste_administratif',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='recherche_referrence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
