# Generated by Django 5.0.2 on 2024-03-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_enterprise_fax_alter_enterprise_localisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='localisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
