# Generated by Django 5.0.2 on 2024-03-22 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_enterprise_localisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_inscription',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
