# Generated by Django 5.0.2 on 2024-03-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_professor_date_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_inscription',
            field=models.DateField(blank=True, null=True),
        ),
    ]
