# Generated by Django 5.0.2 on 2024-03-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_etudiant_date_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='AboutME',
            field=models.TextField(blank=True, null=True),
        ),
    ]
