# Generated by Django 5.0.2 on 2024-03-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_utilisateur_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='entreprise',
            field=models.CharField(default='Self Employed', max_length=100),
        ),
    ]
