# Generated by Django 5.0.2 on 2024-03-22 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_languages_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='date_obtention',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_fin',
            field=models.DateField(),
        ),
    ]
