# Generated by Django 5.0.3 on 2024-03-23 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_languages_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='Add a description to this group here...'),
        ),
        migrations.AddField(
            model_name='group',
            name='profile_banner',
            field=models.ImageField(blank=True, default='profile_pictures/img_banniere.png', upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='group',
            name='target',
            field=models.CharField(default='Public', max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
