# Generated by Django 5.0.2 on 2024-03-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_certification_date_obtention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='Language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skills',
            name='SkillName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
