# Generated by Django 5.0.3 on 2024-03-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_group_created_at_group_description_and_more'),
        ('backend', '0027_group_description_group_profile_banner_group_target_and_more'),
        ('backend', '0027_remove_group_members_group_created_at_and_more'),
    ]

    operations = [
    ]
