# Generated by Django 5.0.2 on 2024-03-22 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_languages_language_alter_skills_skillname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='Nom_Certificat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certification',
            name='date_obtention',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
