# Generated by Django 5.0.2 on 2024-03-24 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_remove_education_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='professors',
        ),
        migrations.CreateModel(
            name='research_profs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Professor', to='backend.professor')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Research', to='backend.research')),
            ],
        ),
    ]
