# Generated by Django 5.0.3 on 2024-03-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_enterprise_localisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='localisation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
