# Generated by Django 5.0.2 on 2024-03-24 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_research_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='utilisateur',
        ),
    ]
