# Generated by Django 5.0.2 on 2024-03-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_remove_research_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='id',
        ),
        migrations.AddField(
            model_name='research',
            name='utilisateur',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
