# Generated by Django 5.0.2 on 2024-03-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_research_id_alter_research_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='id',
        ),
        migrations.AlterField(
            model_name='research',
            name='utilisateur',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
