# Generated by Django 5.0.2 on 2024-03-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_remove_research_id_alter_research_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='research',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
