# Generated by Django 5.0.2 on 2024-03-24 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_remove_research_utilisateur_research_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='research_profs',
        ),
    ]
