# Generated by Django 5.0.2 on 2024-03-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_delete_research_profs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Research',
        ),
    ]
