# Generated by Django 5.0.2 on 2024-03-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_research_research_profs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='research_profs',
        ),
    ]
