# Generated by Django 5.0.2 on 2024-03-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_delete_research_profs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='utilisateur',
        ),
    ]
