# Generated by Django 5.0.2 on 2024-03-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_remove_research_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.utilisateur'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='research_profs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Professor', to='backend.professor')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Research', to='backend.research')),
            ],
        ),
    ]
