# Generated by Django 5.0.2 on 2024-03-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_remove_research_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
