# Generated by Django 5.0.2 on 2024-03-24 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_remove_research_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.utilisateur'),
            preserve_default=False,
        ),
    ]
