# Generated by Django 5.0.3 on 2024-03-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_certification'),
        ('backend', '0048_remove_event_entreprise_event_utilisateur'),
    ]

    operations = [
    ]
