# Generated by Django 5.0.2 on 2024-03-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_event_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
    ]
