# Generated by Django 5.0.2 on 2024-03-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_group_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='utilisateur',
        ),
    ]
