# Generated by Django 5.0.2 on 2024-03-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_alter_usergroup_user'),
        ('backend', '0056_research_utilisateur'),
    ]

    operations = [
    ]
