# Generated by Django 5.0.2 on 2024-03-26 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_merge_20240325_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='background_image',
            field=models.ImageField(upload_to='event_images/'),
        ),
    ]
