# Generated by Django 5.0.2 on 2024-03-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_event_group_alter_event_background_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='background_image',
            new_name='backgroundimage',
        ),
    ]
