# Generated by Django 5.0.2 on 2024-03-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_rename_background_image_event_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateField(),
        ),
    ]
