# Generated by Django 5.0.2 on 2024-03-27 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_alter_event_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassRoomtitle', models.CharField(max_length=100)),
                ('UniqueinvitationCode', models.CharField(max_length=20, unique=True)),
                ('ClassRoomimage', models.ImageField(upload_to='classroom_course_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Admin_Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.professor')),
            ],
        ),
    ]
