# Generated by Django 5.0.2 on 2024-03-29 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_alter_classroom_classroomimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to='postClassroom_files/')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.classroom')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.classroom')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.professor')),
            ],
        ),
    ]
