# Generated by Django 5.0.2 on 2024-03-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_postclassroom_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postclassroom',
            old_name='content',
            new_name='contentPost',
        ),
        migrations.RenameField(
            model_name='postclassroom',
            old_name='file',
            new_name='filePost',
        ),
        migrations.RemoveField(
            model_name='postclassroom',
            name='title',
        ),
    ]
