# Generated by Django 5.0.2 on 2024-03-29 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_qcm_question_answer_studentquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='classroomparticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.classroom')),
                ('Participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.utilisateur')),
            ],
        ),
    ]
