# Generated by Django 5.0.2 on 2024-03-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_conversation_message_messagefile_participant'),
        ('backend', '0064_rename_content_postclassroom_contentpost_and_more'),
    ]

    operations = [
    ]
