# Generated by Django 5.0.2 on 2024-03-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_rename_content_postclassroom_contentpost_and_more'),
        ('backend', '0066_remove_qcm_professor_qcm_classroom_qcm_delai_and_more'),
    ]

    operations = [
    ]
