# Generated by Django 5.0.2 on 2024-03-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_merge_20240329_2019'),
        ('backend', '0067_merge_20240329_2034'),
    ]

    operations = [
    ]
