# Generated by Django 5.0.2 on 2024-03-30 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_rename_creator_postclassroom_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomparticipants',
            name='Classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='backend.classroom'),
        ),
        migrations.AlterField(
            model_name='classroomparticipants',
            name='Participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_classrooms', to='backend.utilisateur'),
        ),
    ]
