# Generated by Django 5.0.2 on 2024-04-01 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_rename_classroom_qcm_qcmclassroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='backend.question'),
        ),
        migrations.AlterField(
            model_name='classroomparticipants',
            name='Classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='backend.classroom'),
        ),
        migrations.AlterField(
            model_name='classroomparticipants',
            name='Participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_classrooms', to='backend.utilisateur'),
        ),
        migrations.AlterField(
            model_name='studentquestion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.utilisateur'),
        ),
    ]
