# Generated by Django 5.0.2 on 2024-03-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_task_created_at_task_filetask_task_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcm',
            old_name='Classroom',
            new_name='QCMClassroom',
        ),
        migrations.RenameField(
            model_name='qcm',
            old_name='delai',
            new_name='QCMdelai',
        ),
        migrations.RenameField(
            model_name='qcm',
            old_name='description',
            new_name='QCMdescription',
        ),
        migrations.RenameField(
            model_name='qcm',
            old_name='title',
            new_name='QCMtitle',
        ),
    ]
