# Generated by Django 5.0.2 on 2024-03-31 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0073_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.utilisateur'),
        ),
    ]
