# Generated by Django 5.0.2 on 2024-04-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_alter_studentquestion_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentQcmfinished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.qcm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.utilisateur')),
            ],
        ),
    ]
