# Generated by Django 5.0.2 on 2024-04-01 05:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_studentqcmfinished'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_Response', models.FileField(upload_to='task_responses/')),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.etudiant')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.task')),
            ],
        ),
    ]
